In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Processed2.csv")

In [3]:
df.head

<bound method NDFrame.head of        Unnamed: 0      id    imdb_id                             title  year  \
0               0     862  tt0114709                         Toy Story  1995
1               1    8844  tt0113497                           Jumanji  1995
2               2   15602  tt0113228                  Grumpier Old Men  1995
3               3   31357  tt0114885                 Waiting to Exhale  1995
4               4   11862  tt0113041       Father of the Bride Part II  1995
5               5     949  tt0113277                              Heat  1995
6               6   11860  tt0114319                           Sabrina  1995
7               7   45325  tt0112302                      Tom and Huck  1995
8               8    9091  tt0114576                      Sudden Death  1995
9               9     710  tt0113189                         GoldenEye  1995
10             10    9087  tt0112346            The American President  1995
11             11   12110  tt0112896       Dracula: Dead and Loving It  1995
12             12   21032  tt0112453                             Balto  1995
13             13   10858  tt0113987                             Nixon  1995
14             14    1408  tt0112760                  Cutthroat Island  1995
15             15     524  tt0112641                            Casino  1995
16             16    4584  tt0114388             Sense and Sensibility  1995
17             17       5  tt0113101                        Four Rooms  1995
18             18    9273  tt0112281    Ace Ventura: When Nature Calls  1995
19             19   11517  tt0113845                       Money Train  1995
20             20    8012  tt0113161                        Get Shorty  1995
21             21    1710  tt0112722                           Copycat  1995
22             22    9691  tt0112401                         Assassins  1995
23             23   12665  tt0114168                            Powder  1995
24             24     451  tt0113627                 Leaving Las Vegas  1995
25             25   16420  tt0114057                           Othello  1995
26             26    9263  tt0114011                      Now and Then  1995
27             27   17015  tt0114117                        Persuasion  1995
28             28     902  tt0112682         The City of Lost Children  1995
29             29   37557  tt0115012                    Shanghai Triad  1995
...           ...     ...        ...                               ...   ...
44084       44084   63266  tt1489253                Phobos. Fear Kills  2010
44085       44085   45527  tt1331329                   The Final Storm  2010
44086       44086  455661  tt6969946                    In a Heartbeat  2017
44087       44087  327237  tt3814486            Blood, Sweat and Tears  2015
44088       44088   84710  tt0036975                      Jungle Woman  1944
44089       44089   39562  tt0889600                 To Be Fat Like Me  2007
44090       44090   14008  tt0294425                       Cadet Kelly  2002
44091       44091   44330  tt0135690   The Scheming Gambler's Paradise  1905
44092       44092   49279  tt0000359      The Man with the Rubber Head  1901
44093       44093   44333  tt0135179          The Living Playing Cards  1905
44094       44094   49277  tt0135122             The Hilarious Posters  1906
44095       44095   49271  tt0127948               The Devilish Tenant  1909
44096       44096   44324  tt0135631           The Untameable Whiskers  1904
44097       44097  122036  tt0224286  The Imperceptable Transmutations  1904
44098       44098   14885  tt0457437  Pooh's Heffalump Halloween Movie  2005
44099       44099   49280  tt0135453                  The One-Man Band  1900
44100       44100  106807  tt0135571  The Fat and Lean Wrestling Match  1900
44101       44101  276895  tt3054038                       Deep Hearts  1981
44102       44102  404604  tt5690142                               Mom  2017
44103       44103  420346  tt4130180                 The Morning After  2015
44104       44104   67179  tt0069215         St. Michael Had a Rooster  1972
44105       44105   84419  tt0038621                  House of Horrors  1946
44106       44106  390959  tt0265736         Shadow of the Blair Witch  2000
44107       44107  289923  tt0252966               The Burkittsville 7  2000
44108       44108  222848  tt0112613                   Caged Heat 3000  1995
44109       44109   30840  tt0102797                        Robin Hood  1991
44110       44110  111109  tt2028550               Century of Birthing  2011
44111       44111   67758  tt0303758                          Betrayal  2003
44112       44112  227506  tt0008536                  Satan Triumphant  1917
44113       44113  461257  tt6980792                          Queerama  2017

                                                  genres  \
0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                         [{'id': 35, 'name': 'Comedy'}]
5      [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
6      [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
7      [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
8      [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
9      [{'id': 12, 'name': 'Adventure'}, {'id': 28, '...
10     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
11     [{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...
12     [{'id': 10751, 'name': 'Family'}, {'id': 16, '...
13     [{'id': 36, 'name': 'History'}, {'id': 18, 'na...
14     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
15     [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
16     [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
17     [{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...
18     [{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...
19     [{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...
20     [{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...
21     [{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...
22     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
23     [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...
24     [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
25                         [{'id': 18, 'name': 'Drama'}]
26     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
27     [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
28     [{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...
29     [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
...                                                  ...
44084  [{'id': 53, 'name': 'Thriller'}, {'id': 27, 'n...
44085  [{'id': 28, 'name': 'Action'}, {'id': 9648, 'n...
44086  [{'id': 10751, 'name': 'Family'}, {'id': 16, '...
44087                      [{'id': 18, 'name': 'Drama'}]
44088  [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...
44089  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
44090                     [{'id': 35, 'name': 'Comedy'}]
44091                                                 []
44092  [{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...
44093                    [{'id': 14, 'name': 'Fantasy'}]
44094  [{'id': 14, 'name': 'Fantasy'}, {'id': 35, 'na...
44095  [{'id': 14, 'name': 'Fantasy'}, {'id': 35, 'na...
44096                                                 []
44097                                                 []
44098  [{'id': 16, 'name': 'Animation'}, {'id': 10751...
44099  [{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...
44100  [{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...
44101                [{'id': 99, 'name': 'Documentary'}]
44102  [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...
44103  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
44104                                                 []
44105  [{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...
44106  [{'id': 9648, 'name': 'Mystery'}, {'id': 27, '...
44107                     [{'id': 27, 'name': 'Horror'}]
44108           [{'id': 878, 'name': 'Science Fiction'}]
44109  [{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...
44110                      [{'id': 18, 'name': 'Drama'}]
44111  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
44112                                                 []
44113                                                 []

                                    production_companies  weighted_rating  \
0         [{'name': 'Pixar Animation Studios', 'id': 3}]         7.684684
1      [{'name': 'TriStar Pictures', 'id': 559}, {'na...         6.877012
2      [{'name': 'Warner Bros.', 'id': 6194}, {'name'...         6.163988
3      [{'name': 'Twentieth Century Fox Film Corporat...         5.678645
4      [{'name': 'Sandollar Productions', 'id': 5842}...         5.625608
5      [{'name': 'Regency Enterprises', 'id': 508}, {...         7.656547
6      [{'name': 'Paramount Pictures', 'id': 4}, {'na...         6.015491
7            [{'name': 'Walt Disney Pictures', 'id': 2}]         5.334081
8      [{'name': 'Universal Pictures', 'id': 33}, {'n...         5.458500
9      [{'name': 'United Artists', 'id': 60}, {'name'...         6.562511
10     [{'name': 'Columbia Pictures', 'id': 5}, {'nam...         6.317635
11     [{'name': 'Columbia Pictures', 'id': 5}, {'nam...         5.636843
12     [{'name': 'Universal Pictures', 'id': 33}, {'n...         6.962285
13     [{'name': 'Hollywood Pictures', 'id': 915}, {'...         6.510528
14     [{'name': 'Le Studio Canal+', 'id': 183}, {'na...         5.610038
15     [{'name': 'Universal Pictures', 'id': 33}, {'n...         7.736957
16     [{'name': 'Columbia Pictures Corporation', 'id...         7.033400
17     [{'name': 'Miramax Films', 'id': 14}, {'name':...         6.425656
18     [{'name': 'O Entertainment', 'id': 5682}, {'na...         6.075001
19              [{'name': 'Columbia Pictures', 'id': 5}]         5.379639
20     [{'name': 'Jersey Films', 'id': 216}, {'name':...         6.284490
21     [{'name': 'Regency Enterprises', 'id': 508}, {...         6.317635
22     [{'name': 'Silver Pictures', 'id': 1885}, {'na...         5.940155
23     [{'name': 'Caravan Pictures', 'id': 175}, {'na...         6.098463
24     [{'name': 'United Artists', 'id': 60}, {'name'...         6.942316
25     [{'name': 'Columbia Pictures', 'id': 5}, {'nam...         6.122448
26               [{'name': 'New Line Cinema', 'id': 12}]         6.234337
27                    [{'name': 'BBC Films', 'id': 288}]         6.367979
28     [{'name': 'Procirep', 'id': 311}, {'name': 'Co...         7.366550
29     [{'name': 'Ministère des Affaires Étrangères',...         5.679355
...                                                  ...              ...
44084  [{'name': 'Art Pictures Studio', 'id': 3451}, ...         5.062878
44085  [{'name': 'Boll Kino Beteiligungs GmbH & Co. K...         4.841880
44086  [{'name': 'Ringling College of Art and Design'...         7.726113
44087                                                 []         5.650576
44088         [{'name': 'Universal Pictures', 'id': 33}]         5.289905
44089                                                 []         5.177159
44090  [{'name': 'Walt Disney Television', 'id': 670}...         5.208480
44091                                                 []         5.219118
44092       [{'name': 'Star Film Company', 'id': 45867}]         6.348851
44093                [{'name': 'Star-Film', 'id': 7159}]         5.423872
44094  [{'name': 'Star-Film', 'id': 7159}, {'name': '...         5.184500
44095       [{'name': 'Star Film Company', 'id': 45867}]         5.647372
44096       [{'name': 'Star Film Company', 'id': 45867}]         5.373817
44097       [{'name': 'Star Film Company', 'id': 45867}]         5.225040
44098        [{'name': 'Walt Disney Pictures', 'id': 2}]         5.274440
44099       [{'name': 'Star Film Company', 'id': 45867}]         5.751342
44100                [{'name': 'Star-Film', 'id': 7159}]         5.459183
44101                                                 []         5.095042
44102  [{'name': 'Mad Films', 'id': 82459}, {'name': ...         5.659724
44103  [{'name': 'Oops Doughnuts Productions', 'id': ...         5.143959
44104                                                 []         5.324381
44105         [{'name': 'Universal Pictures', 'id': 33}]         5.465732
44106                                                 []         5.387202
44107  [{'name': 'Neptune Salad Entertainment', 'id':...         5.342402
44108    [{'name': 'Concorde-New Horizons', 'id': 4688}]         5.147958
44109  [{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...         5.446336
44110             [{'name': 'Sine Olivia', 'id': 19653}]         5.640171
44111  [{'name': 'American World Pictures', 'id': 6165}]         4.998207
44112               [{'name': 'Yermoliev', 'id': 88753}]         5.095042
44113                                                 []         5.095042

                                                overview release_date  \
0      Led by Woody, Andy's toys live happily in his ...   1995-10-30
1      When siblings Judy and Peter discover an encha...   1995-12-15
2      A family wedding reignites the ancient feud be...   1995-12-22
3      Cheated on, mistreated and stepped on, the wom...   1995-12-22
4      Just when George Banks has recovered from his ...   1995-02-10
5      Obsessive master thief, Neil McCauley leads a ...   1995-12-15
6      An ugly duckling having undergone a remarkable...   1995-12-15
7      A mischievous young boy, Tom Sawyer, witnesses...   1995-12-22
8      International action superstar Jean Claude Van...   1995-12-22
9      James Bond must unmask the mysterious head of ...   1995-11-16
10     Widowed U.S. president Andrew Shepherd, one of...   1995-11-17
11     When a lawyer shows up at the vampire's doorst...   1995-12-22
12     An outcast half-wolf risks his life to prevent...   1995-12-22
13     An all-star cast powers this epic look at Amer...   1995-12-22
14     Morgan Adams and her slave, William Shaw, are ...   1995-12-22
15     The life of the gambling paradise – Las Vegas ...   1995-11-22
16     Rich Mr. Dashwood dies, leaving his second wif...   1995-12-13
17     It's Ted the Bellhop's first night on the job....   1995-12-09
18     Summoned from an ashram in Tibet, Ace finds hi...   1995-11-10
19     A vengeful New York transit cop decides to ste...   1995-11-21
20     Chili Palmer is a Miami mobster who gets sent ...   1995-10-20
21     An agoraphobic psychologist and a female detec...   1995-10-27
22     Assassin Robert Rath arrives at a funeral to k...   1995-10-06
23     Harassed by classmates who won't accept his sh...   1995-10-27
24     Ben Sanderson, an alcoholic Hollywood screenwr...   1995-10-27
25     The evil Iago pretends to be friend of Othello...   1995-12-15
26     Waxing nostalgic about the bittersweet passage...   1995-10-20
27     This film adaptation of Jane Austen's last nov...   1995-09-27
28     A scientist in a surrealist society kidnaps ch...   1995-05-16
29     A provincial boy related to a Shanghai crime f...   1995-04-30
...                                                  ...          ...
44084  Rainy summer evening... Young people are arriv...   2010-03-25
44085  A stranger named Silas flees from a devastatin...   2010-01-01
44086  A closeted boy runs the risk of being outed by...   2017-06-01
44087  Bloed, Zweet en Tranen (Blood, Sweat and Tears...   2015-04-02
44088  Paula the ape woman (Acquanetta) is alive and ...   1944-06-01
44089  Pretty, popular, and slim high-schooler Aly Sc...   2007-01-08
44090  Hyperactive teenager Kelly is enrolled into a ...   2002-03-07
44091  A combination gambling den and bawdy house is ...   1905-01-01
44092  A chemist in his laboratory places upon a tabl...   1901-01-01
44093  A bearded magician holds up a large playing ca...   1905-01-01
44094  A wall full of advertising posters comes to life.   1906-01-01
44095  A man rents an apartment and furnishes it in r...   1909-01-01
44096  The background of this picture represents a sc...   1904-03-05
44097  This shows a prince entering upon the stage of...   1904-01-01
44098  It's Halloween in the 100 Acre Wood, and Roo's...   2005-09-13
44099  A band-leader has arranged seven chairs for th...   1900-01-01
44100         A series of fantastical wrestling matches.   1900-01-01
44101  Deep Hearts is a film about the Bororo Fulani,...   1981-01-01
44102  The bliss of a biology teacher’s family life i...   2017-07-07
44103  The Morning After is a feature film that consi...   2015-01-11
44104  Sentenced to life imprisonment for illegal act...   1972-01-01
44105  An unsuccessful sculptor saves a madman named ...   1946-03-29
44106  In this true-crime documentary, we delve into ...   2000-10-22
44107  A film archivist revisits the story of Rustin ...   2000-10-03
44108  It's the year 3000 AD. The world's most danger...   1995-01-01
44109  Yet another version of the classic epic, with ...   1991-05-13
44110  An artist struggles to finish his work while a...   2011-11-17
44111  When one of her hits goes wrong, a professiona...   2003-08-01
44112  In a small town live two brothers, one a minis...   1917-10-21
44113  50 years after decriminalisation of homosexual...   2017-06-09

                            poster_path  norm_year   \
0      /rhIRbceoE9lR4veEXuwCC2wARtG.jpg    0.828767
1      /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg    0.828767
2      /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg    0.828767
3      /16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg    0.828767
4      /e64sOI48hQXyru7naBFyssKFxVd.jpg    0.828767
5      /zMyfPUelumio3tiDKPffaUpsQTD.jpg    0.828767
6      /jQh15y5YB7bWz1NtffNZmRw0s9D.jpg    0.828767
7      /sGO5Qa55p7wTu7FJcX4H4xIVKvS.jpg    0.828767
8      /eoWvKD60lT95Ss1MYNgVExpo5iU.jpg    0.828767
9      /5c0ovjT41KnYIHYuF4AWsTe3sKh.jpg    0.828767
10     /lymPNGLZgPHuqM29rKMGV46ANij.jpg    0.828767
11     /xve4cgfYItnOhtzLYoTwTVy5FGr.jpg    0.828767
12     /gV5PCAVCPNxlOLFM1bKk50EqLXO.jpg    0.828767
13     /cICkmCEiXRhvZmbuAlsA5D9B2rK.jpg    0.828767
14     /odM9973kIv9hcjfHPp6g6BlyTIJ.jpg    0.828767
15     /xo517ibXBDdYQY81j0WIG7BVcWq.jpg    0.828767
16     /lA9HTy84Bb6ZwNeyoZKobcMdpMc.jpg    0.828767
17     /eQs5hh9rxrk1m4xHsIz1w11Ngqb.jpg    0.828767
18     /wRlGnJhEzcxBjvWtvbjhDSU1cIY.jpg    0.828767
19     /jSozzzVOR2kfXgTUuGnbgG2yRFi.jpg    0.828767
20     /vWtDUUgQAsVyvRW4mE75LBgVm2e.jpg    0.828767
21     /80czeJGSoik22fhtUM9WzyjUU4r.jpg    0.828767
22     /xAx5MP7Dg4y85pyS7atX6eWk4Qd.jpg    0.828767
23     /1uRKsxOCtgz0xVqs9l4hYtp4dFm.jpg    0.828767
24     /37qHRJxnSh5YkuaN9FgfNnMl3Tj.jpg    0.828767
25     /qM0BXEQjmnAzlkDZ0tYmV6twqMX.jpg    0.828767
26     /wD6rLdD2Ix3u9YLgE3Do8GyCHoz.jpg    0.828767
27      /si8911IezMvAnQFDvyg1nKzDlD.jpg    0.828767
28     /eVo6ewq4akfyJYy3GXkMsLNzEJc.jpg    0.828767
29     /qcoOCoN7viOhboGwhYXyApdDuiq.jpg    0.828767
...                                 ...         ...
44084  /2SZBMhKfCSse0FVgOdZMJ5TuG8P.jpg    0.931507
44085  /sEP5bLtK5IyQxOFtq5AYz4kUpzD.jpg    0.931507
44086  /wJUJROdLOtOzMixkjkx1aaZGSLl.jpg    0.979452
44087  /aNrh6DfTngUvi7WdpTjLTPzYbTU.jpg    0.965753
44088  /udZ3hvhC52su7UQrGsIyDxK7IQA.jpg    0.479452
44089   /w1TxeDOMS5so83bECaQECW1pV9.jpg    0.910959
44090  /9sQVYo7B9cSexWXoQVzFFijCbD2.jpg    0.876712
44091  /6MwBolpHcddjB3JQyNo2AfB8e3L.jpg    0.212329
44092  /9oqTGZcQf0UwsbA8mKPeJzPRJ5e.jpg    0.184932
44093  /v7V9SA14gmznzpvxbKCtA4BzQ7z.jpg    0.212329
44094  /nLVgY3fYMnRbRzEoz3fF0wrqtCr.jpg    0.219178
44095  /tX3x4Jms6xqVgiet0Ei2Ks0XkAg.jpg    0.239726
44096  /ifWvveLPWWrzitz4oL01YMEokiB.jpg    0.205479
44097  /ifWvveLPWWrzitz4oL01YMEokiB.jpg    0.205479
44098  /yU6byKhpzHG1RFpY5PYM6mfhfU1.jpg    0.897260
44099   /ZLOgI7KjtWby1NEg2pjU2Id60W.jpg    0.178082
44100  /tn5J3PszVETDkKj49nakmeqr8Od.jpg    0.178082
44101  /8jI4ykkIVDmrYgUjDld9i0aulMq.jpg    0.732877
44102  /zZwbntqdfKdVgzH1RoMHa99g0mJ.jpg    0.979452
44103  /rpkDqyKdXahRcZIEC9I02EBSwje.jpg    0.965753

In [4]:
df.head()
df.columns

Index(['Unnamed: 0', 'id', 'imdb_id', 'title', 'year', 'genres',
       'production_companies', 'weighted_rating', 'overview', 'release_date',
       'poster_path', 'norm_year ', 'genre_list'],
      dtype='object')

In [159]:
ff=df.drop(['Unnamed: 0','year','production_companies','release_date'],axis=1)
ff.head()

,id,imdb_id,title,genres,weighted_rating,overview,poster_path,norm_year,genre_list
0,862,tt0114709,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",7.684684,"Led by Woody, Andy's toys live happily in his ...",/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,0.828767,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ..."
1,8844,tt0113497,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",6.877012,When siblings Judy and Peter discover an encha...,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,0.828767,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..."
2,15602,tt0113228,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",6.163988,A family wedding reignites the ancient feud be...,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,0.828767,"[0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ..."
3,31357,tt0114885,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",5.678645,"Cheated on, mistreated and stepped on, the wom...",/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,0.828767,"[0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, ..."
4,11862,tt0113041,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",5.625608,Just when George Banks has recovered from his ...,/e64sOI48hQXyru7naBFyssKFxVd.jpg,0.828767,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ..."

In [160]:
ff.genre_list.head()

0    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...
1    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...
2    [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...
3    [0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, ...
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...
Name: genre_list, dtype: object

In [192]:
j=0
genrelist=[]
genre0=[]
genre1=[]
genre2=[]
genre3=[]
genre4=[]
genre5=[]
genre6=[]
genre7=[]
genre8=[]
genre9=[]
genre10=[]
genre11=[]
genre12=[]
genre13=[]
genre14=[]
genre15=[]
genre16=[]
genre17=[]
genre18=[]
genre19=[]
for i in range(ff.genre_list.size):
    genrelist=[]
    genrelist=ff.genre_list[i][1:-1].split(',')
    genre0.append(int(genrelist[0]))
    genre1.append(int(genrelist[1]))
    genre2.append(int(genrelist[2]))
    genre3.append(int(genrelist[3]))
    genre4.append(int(genrelist[4]))
    genre5.append(int(genrelist[5]))
    genre6.append(int(genrelist[6]))
    genre7.append(int(genrelist[7]))
    genre8.append(int(genrelist[8]))
    genre9.append(int(genrelist[9]))
    genre10.append(int(genrelist[10]))
    genre11.append(int(genrelist[11]))
    genre12.append(int(genrelist[12]))
    genre13.append(int(genrelist[13]))
    genre14.append(int(genrelist[14]))
    genre15.append(int(genrelist[15]))
    genre16.append(int(genrelist[16]))
    genre17.append(int(genrelist[17]))
    genre18.append(int(genrelist[18]))
    genre19.append(int(genrelist[19]))

ff['genre0']=genre0
ff['genre1']=genre1
ff['genre2']=genre2
ff['genre3']=genre3
ff['genre4']=genre4
ff['genre5']=genre5
ff['genre6']=genre6
ff['genre7']=genre7
ff['genre8']=genre8
ff['genre9']=genre9
ff['genre10']=genre10
ff['genre11']=genre11
ff['genre12']=genre12
ff['genre13']=genre13
ff['genre14']=genre14
ff['genre15']=genre15
ff['genre16']=genre16
ff['genre17']=genre17
ff['genre18']=genre18
ff['genre19']=genre19

In [193]:
ff.genre19.head()

0    0
1    1
2    0
3    0
4    0
Name: genre19, dtype: int64

In [194]:
ff.genre19

0        0
1        1
2        0
3        0
4        0
        ..
44109    0
44110    0
44111    0
44112    0
44113    0
Name: genre19, Length: 44114, dtype: int64

In [195]:
ff.genre19[0]+1

1

In [196]:
ff

,id,imdb_id,title,genres,weighted_rating,overview,poster_path,norm_year,genre_list,genre0,...,genre10,genre11,genre12,genre13,genre14,genre15,genre16,genre17,genre18,genre19
0,862,tt0114709,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",7.684684,"Led by Woody, Andy's toys live happily in his ...",/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,0.828767,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,...,0,0,0,0,0,0,1,0,0,0
1,8844,tt0113497,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",6.877012,When siblings Judy and Peter discover an encha...,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,0.828767,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...",0,...,0,0,0,0,0,0,1,0,0,1
2,15602,tt0113228,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",6.163988,A family wedding reignites the ancient feud be...,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,0.828767,"[0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,...,0,0,0,0,0,0,0,0,0,0
3,31357,tt0114885,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",5.678645,"Cheated on, mistreated and stepped on, the wom...",/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,0.828767,"[0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, ...",0,...,0,0,0,0,0,0,0,0,0,0
4,11862,tt0113041,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",5.625608,Just when George Banks has recovered from his ...,/e64sOI48hQXyru7naBFyssKFxVd.jpg,0.828767,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44109,30840,tt0102797,Robin Hood,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",5.446336,"Yet another version of the classic epic, with ...",/fQC46NglNiEMZBv5XHoyLuOWoN5.jpg,0.801370,"[0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ...",0,...,0,0,0,0,0,1,0,0,0,0
44110,111109,tt2028550,Century of Birthing,"[{'id': 18, 'name': 'Drama'}]",5.640171,An artist struggles to finish his work while a...,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,0.938356,"[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ...",0,...,0,0,0,0,0,0,0,0,0,0
44111,67758,tt0303758,Betrayal,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",4.998207,"When one of her hits goes wrong, a professiona...",/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,0.883562,"[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, ...",0,...,0,0,0,1,0,1,0,0,0,0
44112,227506,tt0008536,Satan Triumphant,[],5.095042,"In a small town live two brothers, one a minis...",/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,0.294521,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,...,0,0,0,0,0,0,0,0,0,0
44113,461257,tt6980792,Queerama,[],5.095042,50 years after decriminalisation of homosexual...,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,0.979452,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,...,0,0,0,0,0,0,0,0,0,0

In [200]:
ff=ff.drop(['genre_list'],axis=1)

,id,imdb_id,title,genres,weighted_rating,overview,poster_path,norm_year,genre0,genre1,...,genre10,genre11,genre12,genre13,genre14,genre15,genre16,genre17,genre18,genre19
0,862,tt0114709,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",7.684684,"Led by Woody, Andy's toys live happily in his ...",/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,0.828767,0,0,...,0,0,0,0,0,0,1,0,0,0
1,8844,tt0113497,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",6.877012,When siblings Judy and Peter discover an encha...,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,0.828767,0,0,...,0,0,0,0,0,0,1,0,0,1
2,15602,tt0113228,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",6.163988,A family wedding reignites the ancient feud be...,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,0.828767,0,0,...,0,0,0,0,0,0,0,0,0,0
3,31357,tt0114885,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",5.678645,"Cheated on, mistreated and stepped on, the wom...",/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,0.828767,0,0,...,0,0,0,0,0,0,0,0,0,0
4,11862,tt0113041,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",5.625608,Just when George Banks has recovered from his ...,/e64sOI48hQXyru7naBFyssKFxVd.jpg,0.828767,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44109,30840,tt0102797,Robin Hood,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",5.446336,"Yet another version of the classic epic, with ...",/fQC46NglNiEMZBv5XHoyLuOWoN5.jpg,0.801370,0,0,...,0,0,0,0,0,1,0,0,0,0
44110,111109,tt2028550,Century of Birthing,"[{'id': 18, 'name': 'Drama'}]",5.640171,An artist struggles to finish his work while a...,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,0.938356,0,0,...,0,0,0,0,0,0,0,0,0,0
44111,67758,tt0303758,Betrayal,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",4.998207,"When one of her hits goes wrong, a professiona...",/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,0.883562,0,0,...,0,0,0,1,0,1,0,0,0,0
44112,227506,tt0008536,Satan Triumphant,[],5.095042,"In a small town live two brothers, one a minis...",/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,0.294521,0,0,...,0,0,0,0,0,0,0,0,0,0
44113,461257,tt6980792,Queerama,[],5.095042,50 years after decriminalisation of homosexual...,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,0.979452,0,0,...,0,0,0,0,0,0,0,0,0,0

In [202]:
ff.columns

Index(['id', 'imdb_id', 'title', 'genres', 'weighted_rating', 'overview',
       'poster_path', 'norm_year ', 'genre0', 'genre1', 'genre2', 'genre3',
       'genre4', 'genre5', 'genre6', 'genre7', 'genre8', 'genre9', 'genre10',
       'genre11', 'genre12', 'genre13', 'genre14', 'genre15', 'genre16',
       'genre17', 'genre18', 'genre19'],
      dtype='object')

In [203]:
ff=ff[['id', 'imdb_id', 'title', 'genres',  'overview',
       'poster_path', 'weighted_rating','norm_year ', 'genre0', 'genre1', 'genre2', 'genre3',
       'genre4', 'genre5', 'genre6', 'genre7', 'genre8', 'genre9', 'genre10',
       'genre11', 'genre12', 'genre13', 'genre14', 'genre15', 'genre16',
       'genre17', 'genre18', 'genre19']]

In [204]:
ff

,id,imdb_id,title,genres,overview,poster_path,weighted_rating,norm_year,genre0,genre1,...,genre10,genre11,genre12,genre13,genre14,genre15,genre16,genre17,genre18,genre19
0,862,tt0114709,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,7.684684,0.828767,0,0,...,0,0,0,0,0,0,1,0,0,0
1,8844,tt0113497,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,6.877012,0.828767,0,0,...,0,0,0,0,0,0,1,0,0,1
2,15602,tt0113228,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,6.163988,0.828767,0,0,...,0,0,0,0,0,0,0,0,0,0
3,31357,tt0114885,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,5.678645,0.828767,0,0,...,0,0,0,0,0,0,0,0,0,0
4,11862,tt0113041,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,/e64sOI48hQXyru7naBFyssKFxVd.jpg,5.625608,0.828767,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44109,30840,tt0102797,Robin Hood,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...","Yet another version of the classic epic, with ...",/fQC46NglNiEMZBv5XHoyLuOWoN5.jpg,5.446336,0.801370,0,0,...,0,0,0,0,0,1,0,0,0,0
44110,111109,tt2028550,Century of Birthing,"[{'id': 18, 'name': 'Drama'}]",An artist struggles to finish his work while a...,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,5.640171,0.938356,0,0,...,0,0,0,0,0,0,0,0,0,0
44111,67758,tt0303758,Betrayal,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...","When one of her hits goes wrong, a professiona...",/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,4.998207,0.883562,0,0,...,0,0,0,1,0,1,0,0,0,0
44112,227506,tt0008536,Satan Triumphant,[],"In a small town live two brothers, one a minis...",/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,5.095042,0.294521,0,0,...,0,0,0,0,0,0,0,0,0,0
44113,461257,tt6980792,Queerama,[],50 years after decriminalisation of homosexual...,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,5.095042,0.979452,0,0,...,0,0,0,0,0,0,0,0,0,0

In [208]:
wr_max=ff.weighted_rating.max()
wr_min=ff.weighted_rating.min()
wr_min

1.9174890841056065

In [209]:
divider=wr_max-wr_min
norm_rating=[]
for i in range (ff.weighted_rating.size):
    norm=ff.weighted_rating[i]-wr_min
    norm/=divider
    norm_rating.append(norm)

In [210]:
norm_rating

[0.8245697115578003,
 0.7090921989748861,
 0.6071469130255108,
 0.5377545206214609,
 0.5301715652018714,
 0.8205468113424644,
 0.5859154703207677,
 0.4884902312588119,
 0.5062791277933505,
 0.6641261323785691,
 0.6291146532729287,
 0.5317778555751617,
 0.7212841019978985,
 0.6566937482803872,
 0.527945373955419,
 0.8320434969357836,
 0.7314518042617438,
 0.6445590999153387,
 0.5944239483663425,
 0.49500390867631194,
 0.6243757336880464,
 0.6291146532729287,
 0.5751441804142566,
 0.5977784656954406,
 0.7184290611491031,
 0.601207728978128,
 0.617205138902214,
 0.6363126463581387,
 0.7790841898226725,
 0.5378561435535143,
 0.6211192169775092,
 0.7796846280675225,
 0.5790600020092616,
 0.5307896463161842,
 0.743620572422012,
 0.45551105085109717,
 0.5754067969396152,
 0.7030558565438249,
 0.5364187055259886,
 0.6177229208672803,
 0.6122043512416293,
 0.54768491852498,
 0.4963668246720354,
 0.6504180319187037,
 0.5716092909839824,
 0.8816172812797427,
 0.6792023936187727,
 0.498634646440138,
 0.8798302442539748,
 0.49161840997788325,
 0.6444863596511154,
 0.567309587005811,
 0.4721915913593599,
 0.514861936620023,
 0.45790755890580853,
 0.5572818884564651,
 0.7594592871979338,
 0.4902889666727382,
 0.5507797398522117,
 0.5281208261964496,
 0.6587404960752989,
 0.591842317374911,
 0.44313627837827363,
 0.38326465144711125,
 0.30356705498613645,
 0.48152406131243014,
 0.5366404042611614,
 0.7111073397452384,
 0.7075868713161488,
 0.3745806606783271,
 0.60650922428626,
 0.516290724060185,
 0.4663830685711203,
 0.4116430828531552,
 0.5760044521192683,
 0.5066685022047923,
 0.5598622791935878,
 0.5988468800659885,
 0.6258040230214361,
 0.5994665597190015,
 0.4671036894583109,
 0.4543134727284048,
 0.5279578136658164,
 0.5842045176031013,
 0.4625155683170785,
 0.560614453564032,
 0.5795234458170666,
 0.49763844686864694,
 0.5210547820021145,
 0.3937034930256965,
 0.6217513095027453,
 0.5363293924508297,
 0.5307872427500439,
 0.8376740070349669,
 0.4905472785927229,
 0.504244425833597,
 0.5477133856385219,
 0.6744574099206138,
 0.38304790762202817,
 0.4789180324359828,
 0.64758092812887,
 0.7464436885323757,
 0.4726314986690565,
 0.6075222380268175,
 0.4960852859763451,
 0.4543134727284048,
 0.8232891665078775,
 0.8787458764650594,
 0.6333982159740443,
 0.5176268253180288,
 0.5018816052799517,
 0.5795751906518435,
 0.513409546099984,
 0.5633833981558029,
 0.48152406131243014,
 0.4717929647598097,
 0.47321720463397543,
 0.5235366151780394,
 0.49358179969156274,
 0.8099077858449849,
 0.5799619454452589,
 0.5758106917895305,
 0.3842762756678675,
 0.4615182255240653,
 0.4543134727284048,
 0.4960852859763451,
 0.4872779198599983,
 0.47858208908771416,
 0.46382689262196464,
 0.47776531948297984,
 0.4543134727284048,
 0.5146052494052528,
 0.4902889666727382,
 0.4589888424332613,
 0.5176688996580816,
 0.4543134727284048,
 0.5323730415962888,
 0.6628561168880923,
 0.4960852859763451,
 0.5381614885929696,
 0.6517297358564573,
 0.4587623726365293,
 0.7365258492359369,
 0.5039028941020078,
 0.5462370270991747,
 0.7635941979374405,
 0.6223859152291011,
 0.5715678978943378,
 0.46945942054902845,
 0.7191135219320466,
 0.5406201176787752,
 0.5780870354358275,
 0.5347880380682295,
 0.5803017849977267,
 0.6253924572122567,
 0.4455057690906206,
 0.7109639777606593,
 0.7044564959313032,
 0.6899787710469244,
 0.5848937667146219,
 0.7085997395888075,
 0.50774694844749,
 0.4543134727284048,
 0.5604070119410026,
 0.5046968586616767,
 0.6017675660275829,
 0.5422017868734863,
 0.5092244359962853,
 0.4968029764820057,
 0.38545413080350205,
 0.6740824279187276,
 0.6592705247467064,
 0.5432999108791684,
 0.5235366151780394,
 0.4922109687798803,
 0.6807027998140996,
 0.47048078113106523,
 0.4881497488553916,
 0.5618040911784417,
 0.5016460652086165,
 0.5221289520362474,
 0.5061927174645575,
 0.500034841338169,
 0.6086198609662116,
 0.5135092885218887,
 0.6572911205868095,
 0.5037187779141864,
 0.47637780034408184,
 0.43209131553842717,
 0.6919108993434062,
 0.5175200292176475,
 0.5096921016063356,
 0.5088177788529585,
 0.6775944544729798,
 0.7381205419674561,
 0.4547834025518996,
 0.5195677607394844,
 0.6136831851571095,
 0.5928496059656968,
 0.5196601396888869,
 0.5132735337064774,
 0.49417146958823494,
 0.625132930822117,
 0.5663758246213714,
 0.46676176130432856,
 0.5180388689886402,
 0.5039028941020078,
 0.4526240557441469,
 0.5827334144367574,
 0.6775758274746387,
 0.8150473967989634,
 0.6029912828421568,
 0.4405551683623607,
 0.5647975878003991,
 0.6530769052786418,
 0.5191259683006605,
 0.5613226174813637,
 0.7708365218427793,
 0.6031730308229015,
 0.5567657837388019,
 0.45393600679037427,
 0.46061251263651853,
 0.47752956466756863,
 0.669966234989955,
 0.6996071072585472,
 0.6520255877281476,
 0.6994034613255816,
 0.5935593897458843,
 0.4135513049392637,
 0.7547469187868927,
 0.5905998191103078,
 0.5410555421068881,
 0.4986679438320702,
 0.6676708884714989,
 0.46090243561518235,
 0.5901198212882045,
 0.5115016175418184,
 0.4345895118090569,
 0.4729000087619177,
 0.4807790163983786,
 0.732039731497057,
 0.688289776418616,
 0.5131103188342697,
 0.6480128225593559,
 0.5558922923377092,
 0.5225223530050261,
 0.5477392096241023,
 0.7493054563361414,
 0.4741698854090627,
 0.46019002196273406,
 0.4041993409190708,
 0.560614453564032,
 0.4018857498530399,
 0.5220591733715793,
 0.8819127550705304,
 0.6934785014033159,
 0.7405761197840594,
 0.5700638419041943,
 0.5539176587000789,
 0.6067489465209915,
 0.7411075295214602,
 0.5771096637077728,
 0.5558126643300512,
 0.4905273715908083,
 0.4404962011982045,
 0.5517613185563777,
 0.6144354611778183,
 0.5844580607581161,
 0.4644138663584376,
 0.4723511312020777,
 0.5059599697612804,
 0.6168944929177462,
 0.4854097148698701,
 0.5412009487513038,
 0.5152425701532615,
 0.7040152928265778,
 0.5966770260314367,
 0.7312663671096222,
 0.4303247720554606,
 0.6308098389662258,
 0.8949283508867686,
 0.5197724371680972,
 0.9108390125196633,
 0.5039356757647175,
 0.503525178514048,
 0.5570824891247846,
 0.6329196038432531,
 0.5724962528806657,
 0.5208132651560274,
 0.4543134727284048,
 0.4529197523418308,
 0.45320009023956975,
 0.7106104325062914,
 0.5219581759427507,
 0.6430306364089451,
 0.6023323827828667,
 0.47967823424583855,
 0.7968549566530229,
 0.7922662149598971,
 0.7300821506679647,
 0.4960852859763451,
 0.4691096562502197,
 0.4675382624148289,
 0.46976095414702895,
 0.6338553550765348,
 0.514861936620023,
 0.5086896159236345,
 0.6903436740353288,
 0.6170242199329361,
 0.9392549273889568,
 0.6964215820653072,
 0.49630311495791857,
 0.5641506840858324,
 0.632895061236125,
 0.518152479997175,
 0.502664029685364,
 0.7037214308847731,
 0.5051263317117023,
 0.6297873588124447,
 0.6295700279112472,
 0.48682702805362027,
 0.4923505773550554,
 0.517879117598298,
 0.6768463402022941,
 0.514861936620023,
 0.4919857964351214,
 0.5005783777270424,
 0.7869553269654391,
 0.49410704208307754,
 0.6389184246027861,
 0.5572818884564651,
 0.4786963280655245,
 0.654495733173307,
 0.47899905708029344,
 0.6376243954769587,
 0.7097974204072326,
 0.54781062139533,
 0.669797297164668,
 0.6749681293561147,
 0.6276787720658769,
 0.6234525242035595,
 0.5933047794559126,
 0.5766091554072343,
 0.7597266258880341,
 0.5330479860816912,
 0.4427288849234451,
 0.8964917841456035,
 0.6599252862942903,
 0.5740437203115829,
 0.49507930556721014,
 0.4800928897784872,
 0.5760044521192683,
 0.546976400543987,
 0.5198135378004161,
 0.8672413368042199,
 0.5506312658663397,
 0.6239777772569822,
 0.6669377831293425,
 0.6569386699508581,
 0.533337933172861,
 0.6310397584854233,
 0.5425740119901845,
 0.6268104516986182,
 0.5879176685742575,
 0.4962795061395239,
 0.46634626471578555,
 0.5813041414231814,
 0.6939927756835689,
 0.49119393480069834,
 0.508373307526448,
 0.6916365725799225,
 0.5490713927885754,
 0.5693619293079325,
 0.6295528694060353,
 0.46209954627195166,
 0.4902889666727382,
 0.5250716485985035,
 0.5280840095604733,
 0.44996445467493984,
 0.49702627505242797,
 0.5902812448816888,
 0.49702627505242797,
 0.531253315750891,
 0.32729448787967347,
 0.5364187055259886,
 0.4543134727284048,
 0.5014946242205967,
 0.4254960143856042,
 0.5170755942065389,
 0.5135092885218887,
 0.4543134727284048,
 0.465850663136677,
 0.4543134727284048,
 0.4737937673675457,
 0.465850663136677,
 0.39420970127695604,
 0.4729000087619177,
 0.7146056438720612,
 0.5885328708219695,
 0.5894700993692328,
 0.6445219341346482,
 0.4620848726082176,
 0.6854596729329623,
 0.544605565764219,
 0.4641699292212021,
 0.444455116092409,
 0.41619016493885885,
 0.5497151698961428,
 0.46453442821323937,
 0.4505634300559748,
 0.5096290882205659,
 0.6055307493503638,
 0.5624802471693529,
 0.560901237682677,
 0.511698083454996,
 0.5320170308967896,
 0.5354086307689506,
 0.40775884978938887,
 0.7621316460656063,
 0.453039880258439,
 0.42174539748533013,
 0.8125515896171539,
 0.43857641889175814,
 0.5039354891047939,
 0.5914520031942491,
 0.4203528028937902,
 0.4929546188095888,
 0.45749211392686573,
 0.4646711699141516,
 0.4807790163983786,
 0.6052223076975408,
 0.7670508386002435,
 0.6355583849862092,
 0.5491018879326146,
 0.40571009638057914,
 0.48744302924072824,
 0.7476675510874183,
 0.42826307789697887,
 0.6323453007522493,
 0.4964432831721487,
 0.551292417724617,
 0.5308408506188186,
 0.4615182255240653,
 0.5210547820021145,
 0.6574652956985259,
 0.575789598117972,
 0.6866533946621842,
 0.7478174233066122,
 0.5290919071491794,
 0.4914151748265623,
 0.4156608167448547,
 0.4468958409610423,
 0.47406445038257095,
 0.4956848423155754,
 0.5827157682249039,
 0.5755983064805502,
 0.60297259917247,
 0.4541902424846184,
 0.5627709482769123,
 0.6421747520762465,
 0.45168561759299347,
 0.7123454957279971,
 0.4990655596303744,
 0.42759418779221414,
 0.6803772077536715,
 0.783696698095966,
 0.4468958409610423,
 0.6392356351372201,
 0.4438220096203851,
 0.5916350901183234,
 0.8101681318448535,
 0.6301832540893157,
 0.5695268524186979,
 0.5583149661314376,
 0.551292417724617,
 0.5925286741706074,
 0.46696073545228534,
 0.5113099537374859,
 0.5753803693773247,
 0.48140368102838843,
 0.5466560207303386,
 0.5832774423182375,
 0.6967682001860652,
 0.7108599018580379,
 0.5459889898543011,
 0.6136831851571095,
 0.5235366151780394,
 0.7137689667910294,
 0.5239090539612962,
 0.48525386677735977,
 0.7215767064314359,
 0.7198610821303074,
 0.4212549347853758,
 0.46619758424205293,
 0.5636443502881588,
 0.43333268471401404,
 0.6034027886613982,
 0.7321472735242244,
 0.8015999456646609,
 0.7132263739790167,
 0.6142598985701679,
 0.5254356016769272,
 0.5037967850358687,
 0.49769141331495004,
 0.6309962318634473,
 0.7539609094672172,
 0.5424150608242461,
 0.5430046941944149,
 0.4963138750890592,
 0.34110978377355095,
 0.6316857366553759,
 0.5096481025526537,
 0.6285705654035424,
 0.4881497488553916,
 0.71246032436772,
 0.44904047910337674,
 0.5113625050318671,
 0.9092233710060815,
 0.47989708022140304,
 0.6955675322456092,
 0.49534309569319673,
 0.707198791340016,
 0.6082446160288744,
 0.49360656111859125,
 0.6193350556433236,
 0.6653276640236853,
 0.5045399534189489,
 0.472626700021318,
 0.599722302090572,
 0.6460136512059333,
 0.4357936166042245,
 0.8520178900365428,
 0.5116290055933935,
 0.5729571307695182,
 0.49499262518505127,
 0.4529197523418308,
 0.3200796945822284,
 0.5507616706222777,
 0.45089979693107446,
 0.5457680510145764,
 0.5708428242292155,
 0.8071861331900148,
 0.5940165011946799,
 0.7681601375175358,
 0.48121005123839455,
 0.7844097306149808,
 0.5845650094381187,
 0.590497960278215,
 0.4844926473691314,
 0.44971473154749037,
 0.6540762901988019,
 0.5608363217644224,
 0.4443028203140921,
 0.6110230253521359,
 0.4570031978559928,
 0.6167948549853839,
 0.4706749195474806,
 0.5169606964495791,
 0.5091195440248847,
 0.4543134727284048,
 0.4543134727284048,
 0.6680779652746879,
 0.4794320325233284,
 0.6059947545745561,
 0.4543134727284048,
 0.4587623726365293,
 0.47048686052672206,
 0.45761903167271495,
 0.5820684323572458,
 0.504244425833597,
 0.613048553322207,
 0.48173687159841416,
 0.5432999108791684,
 0.7373983088723377,
 0.7066968331910627,
 0.7808989986077332,
 0.8239898502679917,
 0.8022308947571134,
 0.49507930556721014,
 0.722762748006411,
 0.8809221727023125,
 0.708372013487208,
 0.7945865619950897,
 0.7068185629383898,
 0.7220445983303582,
 0.49417146958823494,
 0.7871094018938397,
 0.4874105683981411,
 0.48570842371384854,
 0.4960852859763451,
 0.5224197753573399,
 0.5766811816765373,
 0.4527498147441226,
 0.4737937673675457,
 0.8211166809065257,
 0.5574813370678365,
 0.5988687581595671,
 0.4379107034096754,
 0.43176447739571927,
 0.636113677318517,
 0.4570031978559928,
 0.5405742367791243,
 0.7341525630201702,
 0.609228156770945,
 0.46696073545228534,
 0.37608623789573803,
 0.5170755942065389,
 0.49691232962048765,
 0.4737937673675457,
 0.4675382624148289,
 0.5219581759427507,
 0.49656102447210176,
 0.603040793353096,
 0.7684377221575704,
 0.48173687159841416,
 0.4790654130960602,
 0.45473042204985653,
 0.6297233476809578,
 0.5048010708040743,
 0.39433036018189616,
 0.49128121626741594,
 0.4419531056290838,
 0.5027461986253002,
 0.4706749195474806,
 0.4982628240027229,
 0.49099775168743387,
 0.5633078344116383,
 0.4737937673675457,
 0.5641506840858324,
 0.5954123711298771,
 0.6811754586380854,
 0.5356693458382852,
 0.5263155784117491,
 0.5091195440248847,
 0.6313413248249679,
 0.4543134727284048,
 0.4886065870385989,
 0.4895802334073782,
 0.4543134727284048,
 0.6770671117776943,
 0.4765683177509744,
 0.600971532579112,
 0.5763481038475693,
 0.5171968342589558,
 0.4675839447680497,
 0.7365775185027085,
 0.5263290022904347,
 0.47308281392902557,
 0.7236513221958638,
 0.7067103178168533,
 0.6461870822527805,
 0.4543134727284048,
 0.6507350217903962,
 0.528784228627995,
 0.49762308006015193,
 0.47776531948297984,
 0.5432233891034557,
 0.5076779245835583,
 0.6420839637577607,
 0.5630877553603744,
 0.5170755942065389,
 0.4543134727284048,
 0.49377682332161815,
 0.5067746302448578,
 0.49762308006015193,
 0.43462138610545203,
 0.4737937673675457,
 0.491883072578942,
 0.4068056546393799,
 0.5267005854760618,
 0.4717929647598097,
 0.5219581759427507,
 0.49283602091291917,
 0.4340280121070352,
 0.4543134727284048,
 0.5699518326830394,
 0.542313304841905,
 0.6139600798042296,
 0.47779425584750035,
 0.4819536886750002,
 0.5360196958221466,
 0.4717929647598097,
 0.5693056643789103,
 0.5225240156582738,
 0.6401976453273048,
 0.4503786033669697,
 0.4813852328552419,
 0.5021296123017202,
 0.44422600666313417,
 0.7332713740161856,
 0.5658917021055687,
 0.56323769435397,
 0.48121005123839455,
 0.721704827145083,
 0.5057872306539701,
 0.5135092885218887,
 0.4543134727284048,
 0.6144679307195956,
 0.4660280441337376,
 0.4872779198599983,
 0.5743215742011746,
 0.567309587005811,
 0.46361866939578067,
 0.48121005123839455,
 0.7070470179711471,
 0.4819662118676319,
 0.6657345004428172,
 0.5938455040836303,
 0.3264629735494087,
 0.4737937673675457,
 0.4543134727284048,
 0.827085479588428,
 0.5044619905874438,
 0.4355888842488042,
 0.4543134727284048,
 0.7556742226409064,
 0.5726125537470013,
 0.41545681021251707,
 0.580309603983596,
 0.4543134727284048,
 0.8607650992210528,
 0.5225746663663708,
 0.5289833152220635,
 0.5060425386340579,
 0.5133796233734125,
 0.5135092885218887,
 0.6574741213415517,
 0.5172035667636284,
 0.4543134727284048,
 0.7144870333116192,
 0.4131431522946074,
 0.3717032317813223,
 0.49656102447210176,
 0.567309587005811,
 0.5609107865722718,
 0.5359562029465639,
 0.49141325746065556,
 0.4543134727284048,
 0.4902889666727382,
 0.4737937673675457,
 0.5475641685022887,
 0.4737937673675457,
 0.49119393480069834,
 0.4543134727284048,
 0.498367156377071,
 0.836576338000527,
 0.45108672828855345,
 0.6816840982846487,
 0.6203263903592953,
 0.5314730469104159,
 0.6918695774708176,
 0.5373401956698092,
 0.6587889210065769,
 0.5235744739539175,
 0.49763844686864694,
 0.4969124091914833,
 0.49914345609133753,
 0.5234640881176821,
 0.4543134727284048,
 0.49762308006015193,
 0.48967997582928285,
 0.4740592726226393,
 0.49161840997788325,
 0.4543134727284048,
 0.5486805013868253,
 0.6679945831133995,
 0.6418020642080202,
 0.5138280636120637,
 0.5995053115459242,
 0.516290724060185,
 0.5199366859493141,
 0.7113589052815545,
 0.5067746302448578,
 0.498745353673765,
 0.472577344411902,
 0.4719180944861291,
 0.32472834779094406,
 0.48173687159841416,
 0.48714382866413325,
 0.465850663136677,
 0.4960852859763451,
 0.520060498991132,
 0.48173687159841416,
 0.5402308707653144,
 0.4902889666727382,
 0.5535004595054138,
 0.49507930556721014,
 0.4742801129367588,
 0.5063767273088382,
 0.4539523263226039,
 0.45048278471911685,
 0.625713715022516,
 0.5440692026407066,
 0.630029870949903,
 0.4891477767120271,
 0.4803805040024906,
 0.54768491852498,
 0.4827957824376226,
 0.703699516150207,
 0.645957382653305,
 0.4707370852608146,
 0.45849315362642146,
 0.731725219587594,
 0.45287252000723294,
 0.48967997582928285,
 0.4543134727284048,
 0.5170755942065389,
 0.4737937673675457,
 0.5527036383850608,
 0.5223606539534633,
 0.5677427043493081,
 0.6195815462615825,
 0.5523731728059803,
 0.48173687159841416,
 0.5214193246769492,
 0.4844926473691314,
 0.4737937673675457,
 0.9385286723698798,
 0.5377545206214609,
 0.6346620274579221,
 0.5100240819756676,
 0.4543134727284048,
 0.516109475748049,
 0.6785731698022531,
 0.45866950445193216,
 0.49902646497993053,
 0.5113979271987527,
 0.42974567586543805,
 0.4613073701547041,
 0.5736824091628746,
 0.4613073701547041,
 0.5126145098864668,
 0.4543134727284048,
 0.49769141331495004,
 0.47506330852828343,
 0.5126885390955558,
 0.5387511128005644,
 0.40066526859767343,
 0.47936559713788923,
 0.5451955121258718,
 0.4729000087619177,
 0.4886065870385989,
 0.49412617779834667,
 0.504244425833597,
 0.5636443502881588,
 0.4737937673675457,
 0.44644819156842713,
 0.5769944667813394,
 0.5530992244108132,
 0.5073131690457614,
 0.5170755942065389,
 0.5861999143440918,
 0.5433032771315046,
 0.7750942010799964,
 0.8388497079356516,
 0.6644874640302686,
 0.683367450682322,
 0.8022125758990883,
 0.8584634778813702,
 0.8890742658354784,
 0.789229064678924,
 0.6672706165596228,
 0.5725002981604566,
 0.8297346207937015,
 0.8579101948089304,
 0.8542580137421009,
 0.7958406553349879,
 0.846732872792448,
 0.8146298820944066,
 0.7574113849863602,
 0.7510255947372118,
 0.8179271392578059,
 0.5769944667813394,
 0.6232333833857062,
 0.7777900354732022,
 0.8151724782024451,
 0.6121455946744879,
 0.8729565011379103,
 0.8591808239819778,
 0.851204599962982,
 0.46904327163751997,
 0.8363362754232831,
 0.5488390363589734,
 0.7954348953711488,
 0.6561651032054002,
 0.8083707918074031,
 0.719866591964662,
 0.6746652808360263,
 0.7139740655483706,
 0.5850322392676838,
 0.6296408154933546,
 0.680370758289822,
 0.6585666913097791,
 0.5576407714147384,
 0.5262817268915853,
 0.7566152404300008,
 0.6191092943616044,
 0.7574207222069331,
 0.6632902029186085,
 0.599904170091032,
 0.6758632447059951,
 0.7492615193302329,
 0.7120028437296124,
 0.7444268255712766,
 0.7427984145477275,
 0.7045005514934142,
 0.7449485494914426,
 0.6043444863490878,
 0.8578833881422261,
 0.8092585436454753,
 0.7639510405679363,
 0.5440777317442378,
 0.5317397866327578,
 0.4690696147377976,
 0.5488390363589734,
 0.4868483149558732,
 0.532248575804783,
 0.48636554067877297,
 0.5230086487219676,
 0.56323769435397,
 0.7422940039883756,
 0.4737739661259097,
 0.4593017082383668,
 0.7806524676063318,
 0.7446295544234575,
 0.5419483369452622,
 0.7560650262769569,
 0.47103066120594894,
 0.6547390181095208,
 0.48928936649999377,
 0.4589888424332613,
 0.5397499802764866,
 0.48173687159841416,
 0.465850663136677,
 0.5561201706110225,
 0.4684104306499261,
 0.5527925925146445,
 0.4543134727284048,
 0.47637780034408184,
 0.4543134727284048,
 0.6252753544984592,
 0.4648788510587878,
 0.5331628487679443,
 0.5136998819411998,
 0.48169035767584895,
 0.6412418989114197,
 0.4628750339877821,
 0.4543134727284048,
 0.6035858115640979,
 0.5967154507338117,

In [212]:
ff['norm_weighted_rating']=norm_rating

c:\users\walee\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [213]:
ff

,id,imdb_id,title,genres,overview,poster_path,weighted_rating,norm_year,genre0,genre1,...,genre11,genre12,genre13,genre14,genre15,genre16,genre17,genre18,genre19,norm_weighted_rating
0,862,tt0114709,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,7.684684,0.828767,0,0,...,0,0,0,0,0,1,0,0,0,0.824570
1,8844,tt0113497,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,6.877012,0.828767,0,0,...,0,0,0,0,0,1,0,0,1,0.709092
2,15602,tt0113228,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,6.163988,0.828767,0,0,...,0,0,0,0,0,0,0,0,0,0.607147
3,31357,tt0114885,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,5.678645,0.828767,0,0,...,0,0,0,0,0,0,0,0,0,0.537755
4,11862,tt0113041,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,/e64sOI48hQXyru7naBFyssKFxVd.jpg,5.625608,0.828767,0,0,...,0,0,0,0,0,0,0,0,0,0.530172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44109,30840,tt0102797,Robin Hood,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...","Yet another version of the classic epic, with ...",/fQC46NglNiEMZBv5XHoyLuOWoN5.jpg,5.446336,0.801370,0,0,...,0,0,0,0,1,0,0,0,0,0.504540
44110,111109,tt2028550,Century of Birthing,"[{'id': 18, 'name': 'Drama'}]",An artist struggles to finish his work while a...,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,5.640171,0.938356,0,0,...,0,0,0,0,0,0,0,0,0,0.532254
44111,67758,tt0303758,Betrayal,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...","When one of her hits goes wrong, a professiona...",/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,4.998207,0.883562,0,0,...,0,0,1,0,1,0,0,0,0,0.440468
44112,227506,tt0008536,Satan Triumphant,[],"In a small town live two brothers, one a minis...",/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,5.095042,0.294521,0,0,...,0,0,0,0,0,0,0,0,0,0.454313
44113,461257,tt6980792,Queerama,[],50 years after decriminalisation of homosexual...,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,5.095042,0.979452,0,0,...,0,0,0,0,0,0,0,0,0,0.454313

In [214]:
ff.columns

Index(['id', 'imdb_id', 'title', 'genres', 'overview', 'poster_path',
       'weighted_rating', 'norm_year ', 'genre0', 'genre1', 'genre2', 'genre3',
       'genre4', 'genre5', 'genre6', 'genre7', 'genre8', 'genre9', 'genre10',
       'genre11', 'genre12', 'genre13', 'genre14', 'genre15', 'genre16',
       'genre17', 'genre18', 'genre19', 'norm_weighted_rating'],
      dtype='object')

In [217]:
ff=ff[['id', 'imdb_id', 'title', 'genres', 'overview', 'poster_path',
        'norm_weighted_rating', 'norm_year ', 'genre0', 'genre1', 'genre2', 'genre3',
       'genre4', 'genre5', 'genre6', 'genre7', 'genre8', 'genre9', 'genre10',
       'genre11', 'genre12', 'genre13', 'genre14', 'genre15', 'genre16',
       'genre17', 'genre18', 'genre19']]

In [218]:
ff

,id,imdb_id,title,genres,overview,poster_path,norm_weighted_rating,norm_year,genre0,genre1,...,genre10,genre11,genre12,genre13,genre14,genre15,genre16,genre17,genre18,genre19
0,862,tt0114709,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,0.824570,0.828767,0,0,...,0,0,0,0,0,0,1,0,0,0
1,8844,tt0113497,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,0.709092,0.828767,0,0,...,0,0,0,0,0,0,1,0,0,1
2,15602,tt0113228,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,0.607147,0.828767,0,0,...,0,0,0,0,0,0,0,0,0,0
3,31357,tt0114885,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,0.537755,0.828767,0,0,...,0,0,0,0,0,0,0,0,0,0
4,11862,tt0113041,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,/e64sOI48hQXyru7naBFyssKFxVd.jpg,0.530172,0.828767,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44109,30840,tt0102797,Robin Hood,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...","Yet another version of the classic epic, with ...",/fQC46NglNiEMZBv5XHoyLuOWoN5.jpg,0.504540,0.801370,0,0,...,0,0,0,0,0,1,0,0,0,0
44110,111109,tt2028550,Century of Birthing,"[{'id': 18, 'name': 'Drama'}]",An artist struggles to finish his work while a...,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,0.532254,0.938356,0,0,...,0,0,0,0,0,0,0,0,0,0
44111,67758,tt0303758,Betrayal,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...","When one of her hits goes wrong, a professiona...",/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,0.440468,0.883562,0,0,...,0,0,0,1,0,1,0,0,0,0
44112,227506,tt0008536,Satan Triumphant,[],"In a small town live two brothers, one a minis...",/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,0.454313,0.294521,0,0,...,0,0,0,0,0,0,0,0,0,0
44113,461257,tt6980792,Queerama,[],50 years after decriminalisation of homosexual...,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,0.454313,0.979452,0,0,...,0,0,0,0,0,0,0,0,0,0

In [222]:
ff.to_csv("classicKNN_file.csv", index=False)